### ISSUE TITLE
Feature Request: [0] All

### ISSUE THREAD

**Issue by chrisnoden** [somnambulist-tech/sync-it#1]
Use this every day. Much easier to work with than the new mutagen functionality.

Working with many projects, it might be handy if the All option (on start and stop) was the first, zero indexed option. I always start and stop all.

It would also save another fraction of a second if the `start` option didn't ask to start the daemon, but just highlighted that this was going to happen when offering up the list of tasks.

**Comment by dave-redfern** [comment]
Add auto-start and [0] All on start/stop. Stop gains [1] All & Daemon for consistency of options. See rel: 1.2.0
